"""
CloudGuard AI
Notification Engine

Sends incident notifications through
Amazon SNS.
"""

import json
import boto3
import os

sns = boto3.client("sns")

SNS_TOPIC_ARN = os.environ["SNS_TOPIC_ARN"]


def send_notification(incident, incident_key):

    event = incident.get("event", {})
    actor = incident.get("actor", {})
    network = incident.get("network", {})
    threat = incident.get("threat", {})
    response = incident.get("response", [])

    message = f"""
CloudGuard AI Security Alert

========================================

Severity:
{threat.get("severity")}

Threat Score:
{threat.get("threat_score")}

Event:
{event.get("event_name")}

Service:
{event.get("event_source")}

Time:
{event.get("event_time")}

========================================

Actor

User:
{actor.get("user")}

Target User:
{actor.get("target_user")}

User Type:
{actor.get("user_type")}

========================================

Network

Source IP:
{network.get("source_ip")}

AWS Region:
{network.get("aws_region")}

User Agent:
{network.get("user_agent")}

========================================

Triggered Rules

"""

    detections = threat.get("detections", [])

    if detections:

        for detection in detections:

            message += f"""
• {detection.get("rule")}
  Severity : {detection.get("severity")}
  Score    : {detection.get("score")}
  Reason   : {detection.get("reason")}
"""

    else:

        message += "\nNo detections.\n"

    message += "\n========================================\n"
    message += "\nAutomated Response\n"

    for action in response:

        message += f"""
• Action : {action.get("action")}
  Status : {action.get("status")}
  Message: {action.get("message")}
"""

    message += f"""

========================================

Incident Report (S3)

{incident_key}

========================================

Generated by CloudGuard AI
"""

    sns.publish(

        TopicArn=SNS_TOPIC_ARN,

        Subject=f"[CloudGuard] {threat.get('severity')} - {event.get('event_name')}",

        Message=message

    )